export { HeroSection } from "./HeroSection";
export { ValuesSection } from "./ValuesSection";
export { NewInSection } from "./NewInSection";
export { CollectionsSection } from "./CollectionsSection";
export { FeaturedProductsSection } from "./FeaturedProductsSection";
export { TrendingProductsSection } from "./TrendingProductsSection";
export { SocialPostsSection } from "./SocialPostsSection";
export { FeedbackSection } from "./FeedbackSection";
export { RevistaSection } from "./RevistaSection";
